### ISSUE TITLE
Proposal for a sublineage of B.1 with 25644T [~40 sequences as of 2022-08-19]

### ISSUE THREAD

**Issue by corneliusroemer** [mpxv-lineages/lineage-designation#10]
There is a relatively large branch on the B.1 polytomy defined by the SNP C25644T.

It has at least 40 sequences in Genbank from a variety of countries including Germany, the UK, the US, Portugal, Mexico.

<img width="1910" alt="image" src="https://user-images.githubusercontent.com/25161793/185586371-579b7871-0df5-4f87-875a-bc438a7f4c48.png">

https://nextstrain.org/monkeypox/hmpxv1?c=gt-nuc_25644&m=div

It could be that this mutation has arisen another time on a different branch, as in the current Nextstrain tree the tree builder seems to place part of this lineage on a separate branch with G63147A

It's not clear to me whether C25644T is homoplasic and/or G63147A is homoplasic. IQtree sometimes put things one way, sometimes another.

<img width="1914" alt="image" src="https://user-images.githubusercontent.com/25161793/185587106-80658a51-81d1-4165-b62e-c1963c4e6397.png">

https://nextstrain.org/monkeypox/hmpxv1?c=gt-nuc_25644,63147&m=div

**Comment by emmahodcroft** [comment]
Hmm, odd that they're not getting put together. We'd probably want to get to the bottom of that before we designate, to ensure it shows up clearly.

**Comment by corneliusroemer** [comment]
We can use a constraint tree if more and better masking doesn't help - right now all the "trouble" seems to stem from these two German RKI sequences - maybe we can have a look at raw reads to see if their reversions are real.

**Comment by emmahodcroft** [comment]
Cornelius, since you bring up the issue above - would you mind writing briefly how we address this? since I'll link to the PR in the designation notes, and this will keep a good record of how this was tackled

**Comment by emmahodcroft** [comment]
Great, thanks! Still good to have a record that it's not an issue any more :)
