### ISSUE TITLE
Proposal for B.1 sublineage with C89906T and G94798A [39 seqs, dominant in Colombia, present worldwide]

### ISSUE THREAD

**Issue by corneliusroemer** [mpxv-lineages/lineage-designation#19]
There's a lineage that makes up the majority of sequences from Colombia - but is also present across Europe.

It's defined by: 89906T and G94798A on top of the B.1 polytomy

<img width="1472" alt="image" src="https://user-images.githubusercontent.com/25161793/191947659-ce1f4f9c-93c5-4501-8667-1f4ea0d57ede.png">

https://nextstrain.org/monkeypox/hmpxv1/2022-09-22?label=id:a12ef095&m=div

**Comment by ha-ruiz75** [comment]
Hello from Colombia.

Thank you! 
I was about to post about this.
So far this one has been identified in two regions of Colombia (most in Antioquia, and one in La Guajira)

Would having the reads would be of help?

**Comment by corneliusroemer** [comment]
Hello @ha-ruiz75, great to hear you were about to post this yourself and thank you very much for sharing sequences from Colombia!

I don't think we need the short reads for designation, but they are always nice to have! Maybe you can upload them to the short reads archive and link them to the consensus sequences that have already been deposited?

https://www.ncbi.nlm.nih.gov/sra
