### ISSUE TITLE
Proposal for B.1 lineage with C18133T, G67611A, G130231A, G159277A [39 seqs, 38x USA, 1x COL]

### ISSUE THREAD

**Issue by corneliusroemer** [mpxv-lineages/lineage-designation#20]
There's a big US lineage that has also been seen once in Colombia with C18133T, G67611A, G130231A, G159277A

<img width="1461" alt="image" src="https://user-images.githubusercontent.com/25161793/191948631-e85b4afa-a76a-41e2-8491-8a296ae3b333.png">

https://nextstrain.org/monkeypox/hmpxv1/2022-09-22?c=gt-nuc_67611,130231,159277&label=id:d0f9a0ce&m=div

**Comment by mbosm** [comment]
I also think this should be named a lineage. Our lab is uploading (in the next few days) 21 sequences from the midwest of the United States that has these four mutations.

**Comment by corneliusroemer** [comment]
Thank you for the heads up @mbosm!
