### ISSUE TITLE
Proposal for B.1 lineage with G175093A [35 seqs, 33x USA, 1x UK, 1x Germany]

### ISSUE THREAD

**Issue by mbosm** [mpxv-lineages/lineage-designation#24]
This is the largest branch on the tree, not counting already labeled lineages.
https://nextstrain.org/groups/illinois-gagnon-private/monkeypox/0928

![image](https://user-images.githubusercontent.com/66961704/192902020-146df926-9343-4177-b01d-21144bd4214c.png)

![image](https://user-images.githubusercontent.com/66961704/192902047-e9dd8fed-03e8-4dfa-8cea-42fc070f4db1.png)

This mutation carries the amino acid change OPG204: D188N

Earliest sample with firm date: 6/17/2022
Latest sample with firm date: 8/04/2022 (The german sample has only 08/2022 as a collection date)

All but one of the samples have secondary mutation C132520T. There are another two samples with G175093A but without C132520T, but they've been sorted elsewhere on the tree. They are hMPX/Human/USA/CA-LAC-PHL-MA00092 and MA00096.

**Comment by mbosm** [comment]
Oh, should probably put all the strain names, too, huh?

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:\Users\MICHAE~1\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\MICHAE~1\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



strain | accession | date | country | division
-- | -- | -- | -- | --
MPXV-USA-IL-IDPH-002 | OP536663 | 2022-08-04 | USA | Illinois
MPXV-USA-IL-IDPH-016 | OP536677 | 2022-07-05 | USA | Illinois
MPXV-USA-IL-IDPH-084 | OP536745 | 2022-07-06 | USA | Illinois
MPXV-USA-IL-IDPH-071 | OP536732 | 2022-07-01 | USA | Illinois
MPXV-USA-IL-IDPH-072 | OP536733 | 2022-06-30 | USA | Illinois
MPXV-USA-IL-IDPH-011 | OP536672 | 2022-07-05 | USA | Illinois
MPXV_USA_2022_IL0020 | OP225962 | 2022-06-02 (2022-06-01 - 2022-06-30) | USA | Illinois
MPXV22/human/USA-OK-86 | OP351285 | 2022-07-27 | USA | Oklahoma
MPXV22/human/USA-OK-66 | OP351281 | 2022-07-22 | USA | Oklahoma
MPXV-USA-IL-IDPH-001 | OP536662 | 2022-07-23 | USA | Illinois
MPXV-USA-IL-IDPH-008 | OP536669 | 2022-07-04 | USA | Illinois
MPXV-USA-IL-IDPH-059 | OP536720 | 2022-07-06 | USA | Illinois
MPXV-USA-IL-IDPH-035 | OP536696 | 2022-06-17 | USA | Illinois
MPXV-USA-IL-IDPH-073 | OP536734 | 2022-06-30 | USA | Illinois
MPXV/Germany/2022/RKI287 | OP270476 | 2022-08-31 (2022-08-04 - 2022-08-31) | Germany |  
MPXV_USA_2022_IL0040 | OP303786 | 2022-06-02 (2022-06-01 - 2022-06-30) | USA | Illinois
MpxV/human/USA/OH-UW-073812/2022 | OP257254 | 2022-08-01 (2022-08-01 - 2022-08-26) | USA | Ohio
MPXV-USA-IL-IDPH-076 | OP536737 | 2022-07-01 | USA | Illinois
MPXV-USA-IL-IDPH-070 | OP536731 | 2022-06-30 | USA | Illinois
MpxV/human/USA/OH-UW-085701/2022 | OP310050 | 2022-08-01 (2022-08-01 - 2022-08-31) | USA | Ohio
MpxV/human/USA/OH-UW-079847/2022 | OP169337 | 2022-07-10 (2022-07-01 - 2022-07-31) | USA | Ohio
MpxV/human/USA/OH-UW-070426/2022 | OP123051 | 2022-07-10 (2022-07-01 - 2022-07-31) | USA | Ohio
MPXV-USA-IL-IDPH-006 | OP536667 | 2022-07-06 | USA | Illinois
MPXV_USA_2022_KY0001 | OP303788 | 2022-06-30 (2022-06-14 - 2022-06-30) | USA | Kentucky
MPXV_USA_2022_IL0023 | OP225966 | 2022-06-30 (2022-06-01 - 2022-06-30) | USA | Illinois
MPXV-USA-IL-IDPH-056 | OP536717 | 2022-07-09 | USA | Illinois
MPXV-USA-IL-IDPH-077 | OP536738 | 2022-07-01 | USA | Illinois
MPXV_USA_2022_MN0006 | OP451003 | 2022-07-01 (2022-07-01 - 2022-07-26) | USA | Minnesota
MPXV_USA_2022_TN0004 | OP450988 | 2022-07-07 (2022-07-01 - 2022-07-31) | USA | Tennessee
MPXV-USA-IL-IDPH-043 | OP536704 | 2022-06-22 | USA | Illinois
MPXV_USA_2022_IL0028 | OP303783 | 2022-06-22 (2022-06-19 - 2022-06-30) | USA | Illinois
hMpxV/UK/LMO-046a/2022 | OP390205 | 2022-07-26 | United Kingdom | Scotland
MpxV/human/USA/WA-UW-082670/2022 | OP310053 | 2022-08-01 (2022-08-01 - 2022-08-26) | USA | Washington
MPXV-USA-IL-IDPH-040 | OP536701 | 2022-06-22 | USA | Illinois
MPXV-USA-IL-IDPH-005 | OP536666 | 2022-06-30 | USA | Illinois



</body>

</html>

**Comment by emmahodcroft** [comment]
Thank you so much for this @mbosm - and apologies it's taken us a while to get to it - it'll be going in very soon!
