### ISSUE TITLE
Proposal for two B.1 sublineages with defining mut: G161797A (Colombia); and G149818A (Germany,Colombia)

### ISSUE THREAD

**Issue by ha-ruiz75** [mpxv-lineages/lineage-designation#30]
Hello, everyone. Cases have been dropping, but we continue sequencing at [INSColombia](https://twitter.com/INSColombia).
I see two likely B.1 sublineages with unique mutations related to cases in Colombia. I would find a designation useful to describe their circulation appropriately and continue surveillance. I appreciate your great work and thank any comments. 

**G161797A (Colombia)**
[https://nextstrain.org/staging/monkeypox/hmpxv1/?gt=nuc.161797A&m=div](https://nextstrain.org/staging/monkeypox/hmpxv1/?gt=nuc.161797A&m=div)

![image](https://user-images.githubusercontent.com/34463016/208167519-b1f04b98-5b2a-49bf-963f-012ac0d68235.png)

**G149818A (Germany,Colombia)**
[https://nextstrain.org/staging/monkeypox/hmpxv1/?gt=nuc.149818A&m=div](https://nextstrain.org/staging/monkeypox/hmpxv1/?gt=nuc.149818A&m=div)

![image](https://user-images.githubusercontent.com/34463016/208168011-4b18f5fd-9b73-4d9b-bbae-c4cd6d1a2e5f.png)

**Comment by rneher** [comment]
Thanks, Hector! These proposal look sensible. Apologies that our response here has been a bit delayed, but we'll move on this right after the holidays!
