### ISSUE TITLE
Proposal for a B.1 sublineage, circulating in the US (CA/WA) during 2023 [36 seqs]

### ISSUE THREAD

**Issue by corneliusroemer** [mpxv-lineages/lineage-designation#34]
Most of (sequenced) global B.1* circulation in 2023 falls into C.1 or B.1.20.

However, there's a third lineage that's currently part of B.1 that's been sizeable in the US alongside B.1.20 with sequences throughout 2023:

<img width="1425" alt="image" src="https://github.com/mpxv-lineages/lineage-designation/assets/25161793/0754695e-c75d-46a0-95dc-3bd2070034b4">

Defining mutations (broad):
- C132698T
- G22415A (unique, i.e. has not occurred elsewhere within B.1 yet)

All sequences just basal to the lineage are from Portugal. One sequence within the proposed lineage was sequenced in Portugal.

https://next.nextstrain.org/mpox/lineage-B.1?gt=nuc.22415A

**Comment by mengfeip** [comment]
Is there an update about the above proposed B.1 sublineage circulating in the US 2023? Multiple GISAID sequences from the US circulating in 2023 are within the same cluster.
