### ISSUE TITLE
Proposal for a B.1 sublineage, circulating in Germany during 2023 [32 seqs]

### ISSUE THREAD

**Issue by corneliusroemer** [mpxv-lineages/lineage-designation#35]
Most of (sequenced) global B.1* circulation in 2023 falls into C.1, B.1.20 and the proposed lineage in #34 

The second biggest lineage in 2023 that is still B.1 behind #34 is a lineage sequenced 13 time in Germany in late 2023.

In 2022, the lineage was also found once in Belgium, and the ancestor was also found in Australia and the US.

<img width="1544" alt="image" src="https://github.com/mpxv-lineages/lineage-designation/assets/25161793/eb4c5ecb-b9b1-49e9-b48f-d0f3d610305d">

https://next.nextstrain.org/mpox/lineage-B.1?branchLabel=aa&gt=nuc.101418T

Defining mutations (broad):
- C34784T (unique, i.e. has not occurred elsewhere within B.1 yet)
- C101418T(unique, i.e. has not occurred elsewhere within B.1 yet)

**Comment by corneliusroemer** [comment]
There are now 32 German sequences from this lineage, but they may well be from 2022 rather than 2023 due to a date error, see: https://github.com/sequence-review/mpox/issues/2

**Comment by corneliusroemer** [comment]
Submitter has confirmed that the dates are correct, so this lineage might be worth designating. Since I opened the issue, around 17 more sequences have been uploaded, all from Germany.

**Comment by mengfeip** [comment]
Is there an update about the above proposed B.1 sublineage circulating in Germany 2023?
