### ISSUE TITLE
B.1 sub-lineage proposal with 53 sequences circulating globally during 2023-2024

### ISSUE THREAD

**Issue by mengfeip** [mpxv-lineages/lineage-designation#38]
Spread internationally with 53 sequences available in GenBank and GISAID up to March 1st, 2024:
- 15 found in North America (USA)
- 36 found in Europe (Germany)
- 2 found in South America (Brazil)

The ancestor was found in North America (USA) and Europe (Germany and Belgium) during 2022.

Has 3 mutations above its parent lineage B.1:
- C34784T
- C101418T
- G109844A

![global_C2_#1](https://github.com/mpxv-lineages/lineage-designation/assets/135363204/c1fee5b8-de06-4c60-b687-854486e36bc9)
![global_C2_#2](https://github.com/mpxv-lineages/lineage-designation/assets/135363204/a155a152-5720-4f38-abc2-532248fcbe81)
![global_C2_#3](https://github.com/mpxv-lineages/lineage-designation/assets/135363204/4042ab1c-e1a9-4667-b7fd-73027b07f9ad)
![global_C2_#4](https://github.com/mpxv-lineages/lineage-designation/assets/135363204/f42ccd27-ab6f-4f95-9221-8cfedab17a66)

**Comment by corneliusroemer** [comment]
Thanks @mengfeip! Could you double check whether this is the same as #35 ? This looks very much like that lineage - which will very soon be designated, the PR is in review #37

**Comment by mengfeip** [comment]
Thank you @corneliusroemer. You are right, they might be the same lineage. There are currently 53 sequences (32 sequences as proposed in #35) from GenBank and GISAID, and I included an additional mutation (G109844A). Looking for their (#37) designation in Nextstrain!

**Comment by corneliusroemer** [comment]
Resolved with #37 

I'm working on the datasets! I hope they are useful
