### ISSUE TITLE
Proposal for B.1.20 sublineage OPG188:E12K

### ISSUE THREAD

**Issue by ammaraziz** [mpxv-lineages/lineage-designation#39]
Lineage B.1.20 is diverse and seems to be expanding in several countries. This proposal is for a new sublineage B.1.20+OPG188:E12K observed in USA and Germany total of 31 sequences from NCBI (soon to be more).

![Screenshot from 2024-06-03 14-04-42](https://github.com/mpxv-lineages/lineage-designation/assets/7768245/c74470ea-89ab-4d26-b357-e59103ae7b52)

https://nextstrain.org/mpox/lineage-B.1?branchLabel=aa&c=gt-OPG188_12&gmax=163107&gmin=161596

Unique mutation:

```
OPG001:*247X
OPG188: E12K
```

First time suggesting a new lineage, please let me know if you need more information.

**Comment by corneliusroemer** [comment]
Thanks for the proposal! 

When you say soon to be more, do you have some from Australia that belong there?

It would be super helpful to have a peek at your sequences do know where to demarcate the lineage.

I'm wondering whether it might be worth designating a B.1.20 sublineage at the big polytomy here:

Time:
<img width="860" alt="Code 2024-06-03 16 24 15" src="https://github.com/mpxv-lineages/lineage-designation/assets/25161793/7a03f8d3-c7d6-4db6-a805-71492bb57947">

Divergence
<img width="1596" alt="Google Chrome 2024-06-03 16 23 45" src="https://github.com/mpxv-lineages/lineage-designation/assets/25161793/cd27b93a-19d5-48b4-8b9f-f18371f1f47c">

There was some epidemiological event of sorts with many descendants.

Both your lineages would be sublineages of this one (called D.1), hence this would be D.1.1/D.1.2

**Comment by ammaraziz** [comment]
> When you say soon to be more, do you have some from Australia that belong there?
Correct, Australian sequences sit in the proposed new sublineage. 

>Both your lineages would be sublineages of this one (called D.1), hence this would be D.1.1/D.1.2
Interesting, I hadn't thought of that. This makes a lot of sense because B.1.20 has several sublineages that could potentially be designated in the future if there's international spread. Happy to support this.

**Comment by corneliusroemer** [comment]
@ammaraziz what do you think of making a cut like this for the first level (i.e. D.1/2/3):

<img width="1524" alt="Brave Browser 2024-10-27 16 56 33" src="https://github.com/user-attachments/assets/2aec5130-afb7-4049-9da2-dca08faba406">

https://next.nextstrain.org/mpox/lineage-B.1?c=gt-nuc_159608,83753,20453&gmax=160608&gmin=19453

Then breaking D.1 (the largest one, yellow) down further into 5 lineages D.1.1/2/3/4/5 (each of them are in at least 2 countries), something like this:

<img width="1538" alt="Brave Browser 2024-10-27 16 59 40" src="https://github.com/user-attachments/assets/297eb456-efbd-494f-99f4-e43031d7619d">

https://next.nextstrain.org/mpox/lineage-B.1?branchLabel=aa&c=gt-nuc_35132,161629,174050,92382,126169&gmax=175050&gmin=34132&m=div

PRs welcome :)
