### ISSUE TITLE
Proposal for B.1.20 sublineage OPG117:S297L #2

### ISSUE THREAD

**Issue by ammaraziz** [mpxv-lineages/lineage-designation#40]
Second proposal for a sublineage of B.1.20. The proposed sublineage is found in USA from public data but soon there will be more from Australia.

![Screenshot from 2024-06-03 14-20-17](https://github.com/mpxv-lineages/lineage-designation/assets/7768245/124f2f2d-58b9-4aa3-84ee-043c1fbca9e2)

https://nextstrain.org/mpox/lineage-B.1?branchLabel=aa&c=gt-OPG117_297&gmax=98406&gmin=96049

Mutations
```
OPG117:S297L
```

New sequences from Australia sit in the lower branch of `B.1.20+OPG117:S297L` which is defined by only nucleotides `G23100A, C50572T, C176642T` 

This one is a tad tricky as there's a clear sub-sub-lineage within the proposed `B.1.20+OPG117:S297L`, which I will call `B.1.20 + OPG117:S297L + OPG029:R108C`

![image](https://github.com/mpxv-lineages/lineage-designation/assets/7768245/db19f690-3f61-4f63-8597-e437d0c4fdca)

Unsure if `B.1.20 + OPG117:S297L + OPG029:R108C` should be designated a new sublineage alongside the above sublineage. It does not meet the criteria of `has spread internationally`

**Comment by corneliusroemer** [comment]
Thanks for the issues @ammaraziz! Could you send me those sequences from Australia? Just the fasta is fine, no need for any metadata! You can either post them here or send via email/Slack. Would be helpful for designation purposes.
