### ISSUE TITLE
Reference sequences for A.2 and A.2.1 lineages are same

### ISSUE THREAD

**Issue by chainorato** [mpxv-lineages/lineage-designation#42]
Hi, I have a question about the reference sequences.

A pair of current reference sequences of A.2 and A.2.1 lineages are stated as [ON674051](https://www.ncbi.nlm.nih.gov/nuccore/ON674051) and [MPXV_USA_2022_FL001](https://www.ncbi.nlm.nih.gov/nuccore/ON674051), respectively.
However, they are same sequences. Are there any specific reasons for that?

**Comment by ammaraziz** [comment]
Good catch. No reason, I think this is a typo of some sorts (probably from copying the formatting from an older proposal).
